#! /bin/sh
( while read P
  do curl --compressed -LO http://mozart.ipipan.waw.pl/~prybak/model_conll2018/$P
  done
) << 'EOF'
model.af_afribooms.pkl
model.ar_padt.pkl
model.bg_btb.pkl
model.bxr_bdt.pkl
model.ca_ancora.pkl
model.cs_cac.pkl
model.cs_fictree.pkl
model.cs_pdt.pkl
model.cu_proiel.pkl
model.da_ddt.pkl
model.de_gsd.pkl
model.el_gdt.pkl
model.en_ewt.pkl
model.en_gum.pkl
model.en_lines.pkl
model.es_ancora.pkl
model.et_edt.pkl
model.eu_bdt.pkl
model.fa_seraji.pkl
model.fi_ftb.pkl
model.fi_tdt.pkl
model.fr_gsd.pkl
model.fr_sequoia.pkl
model.fr_spoken.pkl
model.fro_srcmf.pkl
model.ga_idt.pkl
model.gl_ctg.pkl
model.gl_treegal.pkl
model.got_proiel.pkl
model.grc_perseus.pkl
model.grc_proiel.pkl
model.he_htb.pkl
model.hi_hdtb.pkl
model.hr_set.pkl
model.hsb_ufal.pkl
model.hu_szeged.pkl
model.hy_armtdp.pkl
model.id_gsd.pkl
model.it_isdt.pkl
model.it_postwita.pkl
model.ja_gsd.pkl
model.kk_ktb.pkl
model.kmr_mg.pkl
model.ko_gsd.pkl
model.ko_kaist.pkl
model.la_ittb.pkl
model.la_perseus.pkl
model.la_proiel.pkl
model.lv_lvtb.pkl
model.nl_alpino.pkl
model.nl_lassysmall.pkl
model.no_bokmaal.pkl
model.no_nynorsk.pkl
model.no_nynorsklia.pkl
model.pl_lfg.pkl
model.pl_sz.pkl
model.pt_bosque.pkl
model.ro_rrt.pkl
model.ru_syntagrus.pkl
model.ru_taiga.pkl
model.sk_snk.pkl
model.sl_ssj.pkl
model.sl_sst.pkl
model.sme_giella.pkl
model.sr_set.pkl
model.sv_lines.pkl
model.sv_talbanken.pkl
model.tr_imst.pkl
model.ug_udt.pkl
model.uk_iu.pkl
model.ur_udtb.pkl
model.vi_vtb.pkl
model.zh_gsd.pkl
EOF
